version: "3"
services: 
  node-app:
    build: .
    #you should not put (ports:) in docker-compose.yml file if the dev and prod ports are different
    ports: 
      - "3000:3000"
    environment: 
      - PORT=3000
  mongo:
    image: mongo
    environment: 
      - MONGO_INITDB_ROOT_USERNAME=vikas
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes: 
      - mongo-db:/data/db

volumes: 
  mongo-db: