version: "3"
services: 
  node-app:
    build: .
    #you should not put (ports:) in docker-compose.yml file if the dev and prod ports are different
    ports: 
      - "3000:3000"
    environment: 
      - PORT=3000

#Note:- these variables are shared between dev and prod