version: "3"
services:
  node-app:
    # The below build will override the build in docker-composer.yml file
    # and the build.args.NODE_ENV will be used in Dockerfile ARG NODE_ENV value
    build:
      context: .
      args:
        NODE_ENV: production
    environment:
      - NODE_ENV=production
      - MONGO_USER=vikas_prod
      - MONGO_PASSWORD=password_prod
    command: node index.js

  mongo:
    image: mongo
    environment: 
      - MONGO_INITDB_ROOT_USERNAME=vikas_prod
      - MONGO_INITDB_ROOT_PASSWORD=password_prod