version: "3"
services:
  node-app:
    # The below build will override the build in docker-composer.yml file
    # and the build.args.NODE_ENV will be used in Dockerfile ARG NODE_ENV value
    build:
      context: .
      args:
        NODE_ENV: development
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - MONGO_USER=vikas
      - MONGO_PASSWORD=password
    command: npm run dev

  mongo:
    image: mongo
    environment: 
      - MONGO_INITDB_ROOT_USERNAME=vikas
      - MONGO_INITDB_ROOT_PASSWORD=password